apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: om-default-events
  namespace: metering
  labels:
    strimzi.io/cluster: openmeter
spec:
  topicName: om_default_events
  partitions: 10
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
