---
apiVersion: v1
kind: Namespace
metadata:
  name: tidb-admin
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tidb-operator
  namespace: flux-system
spec:
  interval: 1m
  url: "https://github.com/pingcap/tidb-operator"
  ref:
    tag: "v1.5.2" 
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tidb-operator-crd
  namespace: flux-system
spec:
  interval: 5m
  path: "./manifests/crd.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: tidb-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pingcap
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://charts.pingcap.org/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tidb-operator
  namespace: tidb-admin
spec:
  interval: 1h
  releaseName: tidb-operator
  timeout: 10m
  maxHistory: 2
  chart:
    spec:
      chart: tidb-operator
      sourceRef:
        kind: HelmRepository
        name: pingcap
        namespace: flux-system
---