apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: altinity
  namespace: flux-system
spec:
  interval: 24h
  url: https://docs.altinity.com/clickhouse-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: altinity-clickhouse-operator
  namespace: metering
spec:
  interval: 30m
  chart:
    spec:
      chart: altinity-clickhouse-operator
      sourceRef:
        kind: HelmRepository
        name: altinity
        namespace: flux-system
      interval: 12h