apiVersion: v1
kind: Namespace
metadata:
  name: confluent
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: confluentinc
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://packages.confluent.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: confluent
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  releaseName: confluent-for-kubernetes
  timeout: 10m
  maxHistory: 2
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: confluentinc
        namespace: flux-system
  values:
    kRaftEnabled: true