---
apiVersion: v1
kind: Namespace
metadata:
  name: flink
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flink-operator-repo
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://downloads.apache.org/flink/flink-kubernetes-operator-1.7.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flink-kubernetes-operator
  namespace: flink
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  releaseName: flink-kubernetes-operator
  timeout: 10m
  maxHistory: 2
  chart:
    spec:
      chart: flink-kubernetes-operator
      sourceRef:
        kind: HelmRepository
        name: flink-operator-repo
        namespace: flux-system
  values:
    rbac:
      nodesRule:
        create: true
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
---

