apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    cluster:
      name: orb
    externalServices:
      prometheus:
        secret:
          create: false
          name: "prometheus-k8s-monitoring"
          namespace: "default"
      tempo:
         secret:
          create: false
          name: "tempo-k8s-monitoring"
          namespace: "default"
    metrics:
      cost:
        enabled: false
    opencost:
      enabled: false
    logs:
      pod_logs:
        enabled: false
      cluster_events:
        enabled: false
      enabled: false
    traces:
      enabled: true
  timeout: '120s'