apiVersion: v1
kind: Namespace
metadata:
  name: testkube
---  
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubeshop
  namespace: flux-system
spec:
  interval: 30m0s
  url:  https://kubeshop.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testkube
  namespace: testkube
spec:
  interval: 1h
  releaseName: testkube
  timeout: 15m
  maxHistory: 2
  chart:
    spec:
      chart: testkube
      sourceRef:
        kind: HelmRepository
        name: kubeshop
        namespace: flux-system
  values:
    testkube-api:
      cloud:
        key: tkcagnt_fb06ae864f386433f35efabc7e7936
        orgId: tkcorg_3fed6319dfba2091 
        envId: tkcenv_c74b127c844774d8 
        url: agent.testkube.io:443
      minio:
        enabled: false
    mongodb:
      enabled: false    
    testkube-dashboard:
      enabled: false
    nats.natsbox:
      nodeSelector: {}
