apiVersion: v1
data:
    host: ENC[AES256_GCM,data:UPZRvI2KzcbdyeOPdPh9OxyIQ6YFQHxyeYenljMl/ck0CnaQVGXI6yVWGyIhs7PqKyeex6fS2rX+zhypUnSOyPZLESWqrCNn,iv:N9g2fvcTjD3RpcLjzXX06hTJdzNDVKg9Uw7eFKF1hxw=,tag:5vM8tAOjpGUT1L1TIcjbDA==,type:str]
    password: ENC[AES256_GCM,data:iuCvsLjR/kMkPb1nSG4HxplrGAf0iuwuNzoJKrJqHqKMRyDzu17I1jokKdpNq6Mf52xwmnAsGdTUJ/oUfsjYOY4aMG1xZ6gVaRQm8bEF/VlExBJpeHo/Gd+Cc8rb8quyCPgqf+HRufS7jLxoyqm7FCRRQdXIQH4vZCfOo3758lAVDOTwAjCgx5MO4AnLcded9izH08qBcpz2L3QvkZJz7H6vmS7s1GTalNSoq1q26GK1iwDtQSE6w7LpvJ5V1cmgnFP79Q8efcLbUFYflBUtdGDcrr5GtFZKrhgK0Gx95Ns=,iv:++JQouASrS5rPaedkmftc0UDuVDkhgWpmwHRtHXaJ8I=,tag:clZf+Mumr0bmQUZh/4VDXw==,type:str]
    username: ENC[AES256_GCM,data:ryR+CLgzHFWCJn8Y,iv:Uuf/0UMk6+ujF7l5tK4jXQZjqD4A3pcPoYliaihhIoA=,tag:1MKHr8YfFcKj3UduTJNSgA==,type:str]
kind: Secret
metadata:
    name: prometheus-k8s-monitoring
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-04T16:50:58Z"
    mac: ENC[AES256_GCM,data:kz5D8XAk3IpPrXFDqKIcnyEjZ77xZR1gDd7MXXrmJq3oNOLCkkLdxS0Iq9mFtwUgwv/ZxNSQ0Y0yay8vk8UoJ+UMSKA8FD4fG+fW3r8TmlObXh+1i/kH/OPx3hCAwxv98J2kWQ1h5CbKOMh8O4YzdInyR+ixhTTMmKcpQuLU9KY=,iv:TGqs041ovObJzQAdsM7tWDKBLBF65Top+WamNtre2vU=,tag:dpWfsWllOS1xb5xqsPDYlQ==,type:str]
    pgp:
        - created_at: "2024-02-04T16:50:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/jnXxrcxi9zAQ//R7ASjVzuWNzh81hLm+BYF/9IiLsggTI61oamwWvgdd6Y
            YeCruEo6mcjqLLmBU7InTuNcUIbU4baafBLRRYOko4d7JGWPz+Hry+kGl3DaVxFn
            tnZAj9qcnyHuTAyUrnBAqdClsdR10YWuEQjEfACXV29BMrrak9IJJnghjO1TDhkM
            p8skIyzvV0GMjYx3fYauNfFk7wkvsSlNMgJPNRhWHJAa8LIUtFVpEJ8Q6Z0jt0LU
            Zn35WPXIf0t+wwtfwxTHd1+tJ2J2u3Zzt1RfhKMRgxK9o52PobDt4kNivACfihlq
            NvKtX+rKaqfj0jQUJ9waSpME2qEGEXpDNo9e8kVtvCVQ6goccp7AYLZ5/YFaYh1L
            Z9O2Cu7PabzXnA1E126UPb3ry0bJuW6JQ+e3dqn7jX77HKKFwJN7M5lEXpbJc+3G
            8h/pagXW9DWDgCygiBGFgWDwMYsNJrpUFNDg87+rkRkbMTDP3U3IwpK13x0YydAv
            dIjoUzzcmBIKuQhApMMsseDmeWe4HIO3eeyimuvA4nzyjdFDuXdghFKdwmU/4LQN
            HrYCN2YWpaAF+NovODVGtyCHDheENutWYl4YVxVOYKhF4jjvNcZ6FB34z0f5bZWA
            WD/Q9Qdh78pRjaHtg6Nk539d3BZ6sHNSbKV73ZLCcliGSKXj2ISwGn/HFKQlsWLU
            aAEJAhAVgS+WfznJt2kTjwkad7IdpLbOyMt172LaZBvtEXVAFm/6qIFdkLZF/wMS
            kE3geu++E3oR/8Oi+rIRx0mpDgpj2SI5g0Errtz3kSzdygCIWqNM4p1IoedJZHIz
            YaYuD24j1PHu
            =QTmL
            -----END PGP MESSAGE-----
          fp: FAACA71B78C681AC46FBB9F305ACA9542F580F5E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: k8s-monitoring/templates/trace-service-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
    name: tempo-k8s-monitoring
    namespace: default
type: Opaque
data:
    host: ENC[AES256_GCM,data:SgCspsbJZAe1qmKQiXoc3catR/GjkjXIIGwLyaav4rm8JFudHWr4k/S99V8roVUDX4GtIPIEQjRSLxHuh2uAObPZisXV+cZl,iv:wVjAepKEWyxEZQYctcyBKU/p8QemcZS0c0DyMw9Vizc=,tag:JATRh0/zshY+aN+UjhikKg==,type:str]
    username: ENC[AES256_GCM,data:LPRDGOuIJVk=,iv:Trzza+wVSvQXlUSwGxq5yX7yCpuHVRL5eOHUiaceNXs=,tag:1OnJDaAm9ZLe+zql5A29cA==,type:str]
    password: ENC[AES256_GCM,data:QM0bKR/QJI8i2EoeBTQN3AXWpLxZIh/KoxP/TRRiCbgYfmxoygG/5K7LZAMLCmDDBGtLEh2c28VLRx17mJxM0Cfhe9QqeZij0UNVVw4Cs0AnFZSvgsAYXlG24Cq6s/gZWl0WFhJ15b3LI/hWpqUg9KyXWjqMxqD//z+SyL9zUQBvDg5kr5M/uZJGvuQx8buL297P4VK4AwifnqGZF3WoCf8PEt9S9JHNCvcFZ3ORcFviryUg63MKXma6TFWxMj+N9LqafNhVwx2SbAmmtdrHNWafiVJ1w4bTaKg2Wy/KDds=,iv:Q9JBuBmTQlTfnATgPDwF1NK5uboS0YO7wC5d49RnTSc=,tag:keka9sOJ1N6ifzqE4Cqu1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-04T16:50:58Z"
    mac: ENC[AES256_GCM,data:kz5D8XAk3IpPrXFDqKIcnyEjZ77xZR1gDd7MXXrmJq3oNOLCkkLdxS0Iq9mFtwUgwv/ZxNSQ0Y0yay8vk8UoJ+UMSKA8FD4fG+fW3r8TmlObXh+1i/kH/OPx3hCAwxv98J2kWQ1h5CbKOMh8O4YzdInyR+ixhTTMmKcpQuLU9KY=,iv:TGqs041ovObJzQAdsM7tWDKBLBF65Top+WamNtre2vU=,tag:dpWfsWllOS1xb5xqsPDYlQ==,type:str]
    pgp:
        - created_at: "2024-02-04T16:50:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/jnXxrcxi9zAQ//R7ASjVzuWNzh81hLm+BYF/9IiLsggTI61oamwWvgdd6Y
            YeCruEo6mcjqLLmBU7InTuNcUIbU4baafBLRRYOko4d7JGWPz+Hry+kGl3DaVxFn
            tnZAj9qcnyHuTAyUrnBAqdClsdR10YWuEQjEfACXV29BMrrak9IJJnghjO1TDhkM
            p8skIyzvV0GMjYx3fYauNfFk7wkvsSlNMgJPNRhWHJAa8LIUtFVpEJ8Q6Z0jt0LU
            Zn35WPXIf0t+wwtfwxTHd1+tJ2J2u3Zzt1RfhKMRgxK9o52PobDt4kNivACfihlq
            NvKtX+rKaqfj0jQUJ9waSpME2qEGEXpDNo9e8kVtvCVQ6goccp7AYLZ5/YFaYh1L
            Z9O2Cu7PabzXnA1E126UPb3ry0bJuW6JQ+e3dqn7jX77HKKFwJN7M5lEXpbJc+3G
            8h/pagXW9DWDgCygiBGFgWDwMYsNJrpUFNDg87+rkRkbMTDP3U3IwpK13x0YydAv
            dIjoUzzcmBIKuQhApMMsseDmeWe4HIO3eeyimuvA4nzyjdFDuXdghFKdwmU/4LQN
            HrYCN2YWpaAF+NovODVGtyCHDheENutWYl4YVxVOYKhF4jjvNcZ6FB34z0f5bZWA
            WD/Q9Qdh78pRjaHtg6Nk539d3BZ6sHNSbKV73ZLCcliGSKXj2ISwGn/HFKQlsWLU
            aAEJAhAVgS+WfznJt2kTjwkad7IdpLbOyMt172LaZBvtEXVAFm/6qIFdkLZF/wMS
            kE3geu++E3oR/8Oi+rIRx0mpDgpj2SI5g0Errtz3kSzdygCIWqNM4p1IoedJZHIz
            YaYuD24j1PHu
            =QTmL
            -----END PGP MESSAGE-----
          fp: FAACA71B78C681AC46FBB9F305ACA9542F580F5E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-04T16:50:58Z"
    mac: ENC[AES256_GCM,data:kz5D8XAk3IpPrXFDqKIcnyEjZ77xZR1gDd7MXXrmJq3oNOLCkkLdxS0Iq9mFtwUgwv/ZxNSQ0Y0yay8vk8UoJ+UMSKA8FD4fG+fW3r8TmlObXh+1i/kH/OPx3hCAwxv98J2kWQ1h5CbKOMh8O4YzdInyR+ixhTTMmKcpQuLU9KY=,iv:TGqs041ovObJzQAdsM7tWDKBLBF65Top+WamNtre2vU=,tag:dpWfsWllOS1xb5xqsPDYlQ==,type:str]
    pgp:
        - created_at: "2024-02-04T16:50:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/jnXxrcxi9zAQ//R7ASjVzuWNzh81hLm+BYF/9IiLsggTI61oamwWvgdd6Y
            YeCruEo6mcjqLLmBU7InTuNcUIbU4baafBLRRYOko4d7JGWPz+Hry+kGl3DaVxFn
            tnZAj9qcnyHuTAyUrnBAqdClsdR10YWuEQjEfACXV29BMrrak9IJJnghjO1TDhkM
            p8skIyzvV0GMjYx3fYauNfFk7wkvsSlNMgJPNRhWHJAa8LIUtFVpEJ8Q6Z0jt0LU
            Zn35WPXIf0t+wwtfwxTHd1+tJ2J2u3Zzt1RfhKMRgxK9o52PobDt4kNivACfihlq
            NvKtX+rKaqfj0jQUJ9waSpME2qEGEXpDNo9e8kVtvCVQ6goccp7AYLZ5/YFaYh1L
            Z9O2Cu7PabzXnA1E126UPb3ry0bJuW6JQ+e3dqn7jX77HKKFwJN7M5lEXpbJc+3G
            8h/pagXW9DWDgCygiBGFgWDwMYsNJrpUFNDg87+rkRkbMTDP3U3IwpK13x0YydAv
            dIjoUzzcmBIKuQhApMMsseDmeWe4HIO3eeyimuvA4nzyjdFDuXdghFKdwmU/4LQN
            HrYCN2YWpaAF+NovODVGtyCHDheENutWYl4YVxVOYKhF4jjvNcZ6FB34z0f5bZWA
            WD/Q9Qdh78pRjaHtg6Nk539d3BZ6sHNSbKV73ZLCcliGSKXj2ISwGn/HFKQlsWLU
            aAEJAhAVgS+WfznJt2kTjwkad7IdpLbOyMt172LaZBvtEXVAFm/6qIFdkLZF/wMS
            kE3geu++E3oR/8Oi+rIRx0mpDgpj2SI5g0Errtz3kSzdygCIWqNM4p1IoedJZHIz
            YaYuD24j1PHu
            =QTmL
            -----END PGP MESSAGE-----
          fp: FAACA71B78C681AC46FBB9F305ACA9542F580F5E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
