---
apiVersion: v1
kind: Namespace
metadata:
  name: tidb-admin
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pingcap
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://charts.pingcap.org/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tidb-operator
  namespace: tidb-admin
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  releaseName: tidb-operator
  timeout: 10m
  maxHistory: 2
  chart:
    spec:
      chart: tidb-operator
      sourceRef:
        kind: HelmRepository
        name: pingcap
        namespace: flux-system