apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: sysbench-nodepool
spec:
  template:
    metadata:
      labels:
        dedicated: sysbench
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      taints:
        - key: dedicated
          value: sysbench
          effect: NoSchedule
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: "100"  
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench
  namespace: default
spec:
  completions: 2 # Total number of times the job will run
  parallelism: 2 # Number of Pods running at the same time
  template:
    metadata:
      name: sysbench
    spec:
      containers:
        - name: sysbench
          image: gcr.io/pingcap-public/pingcap/tidb-sysbench:latest
          command: ["/usr/local/bin/sysbench"]
          args:
            - oltp_write_only
            - --threads=400
            - --db-driver=mysql
            - --mysql-host=tidb-tidb.tidb-cluster.svc.cluster.local
            - --mysql-port=4000
            - --mysql-user=root
            - --mysql-password=7KCX2-/9@Ok0m
            - --mysql-db=test
            - --events=0
            - --time=300
            - --tables=10
            - --table_size=10000000
            - --range_selects=off
            - --db-ps-mode=disable
            - --report-interval=1
            - run
          resources:
            limits:
              cpu: "31000m"
              memory: "110Gi"
            requests:
              cpu: "31000m"
              memory: "96Gi"
      nodeSelector:
        dedicated: "sysbench"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "sysbench"
          effect: "NoSchedule"
      restartPolicy: Never
  backoffLimit: 0
# az aks nodepool add --name sysbench \
#     --cluster-name karpuktest    \
#     --resource-group mobius-prod-rg \
#     --node-vm-size Standard_D32as_v5 \
#     --zones 1 \
#     --aks-custom-headers EnableAzureDiskFileCSIDriver=true \
#     --node-count 1 \
#     --labels dedicated=sysbench \
#     --node-taints dedicated=sysbench:NoSchedule

