apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: xk6-executor
  namespace: testkube
spec:
  executor_type: job
  image: ghcr.io/rverma-dev/k6:sha-d8ebfc1
  types:
    - k6/script
    - k6/run
    - k6/cloud
