apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: xk6-executor
  namespace: testkube
spec:
  args:
  - <k6Command>
  - <envVars>
  - <runPath>
  command:
  - k6
  content_types:
  - string
  - file-uri
  - git-file
  - git-dir
  - git
  executor_type: job
  features:
  - artifacts
  image: ghcr.io/rverma-dev/k6:sha-d8ebfc1
  types:
  - xk6/script
  - xk6/run
  - xk6/cloud
