apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: xk6-executor
  namespace: testkube
spec:
  executor_type: job
  image: kubeshop/testkube-k6-executor:latest
  types:
  - k6/script
  - k6/run
  - k6/cloud