apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  name: ge-test
  namespace: testkube
spec:
  repository:
    type: git
    uri: https://github.com/rverma-dev/ge-test.git
    usernameSecret:
      name: ge-test-source-secrets
      key: git-username
---
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: create-ge
  namespace: testkube
  labels:
    executor: xk6-executor
    test: demo
    test-type: xk6-script
spec:
  type: xk6/script
  content:
    type: git-dir
    repository:
      branch: main
      path: dist
  source: ge-test
  executionRequest:
    variables:
      TIDB_PASSWORD:
        name: TIDB_PASSWORD
        type: secret
        valueFrom:
          secretKeyRef:
            name: sample-testvars
            key: TIDB_PASSWORD
    args:
      - "--summary-export"
      - "/home/k6/create-ge.json"
      - "tidb-createGE-test.js"
    executePostRunScriptBeforeScraping: false
    artifactRequest:
      dirs:
        - /home/k6
      masks:
        - .*\.json
      sharedBetweenPods: false

---
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: insert-data
  namespace: testkube
  labels:
    executor: xk6-executor
    test: demo
    test-type: xk6-script
spec:
  type: xk6/script
  content:
    type: git-dir
    repository:
      branch: main
      path: dist
  source: ge-test
  executionRequest:
    variables:
      TIDB_PASSWORD:
        name: TIDB_PASSWORD
        type: secret
        valueFrom:
          secretKeyRef:
            name: sample-testvars
            key: TIDB_PASSWORD
    args:
      - "--summary-export"
      - "/home/k6/insert-data.json"
      - tidb-insertData-test.js 
    artifactRequest:
      dirs:
        - /home/k6
      masks:
        - .*\.json
      sharedBetweenPods: false
---
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: read-data
  namespace: testkube
  labels:
    executor: xk6-executor
    test: demo
    test-type: xk6-script
spec:
  type: xk6/script
  content:
    type: git-dir
    repository:
      branch: main
      path: dist
  source: ge-test
  executionRequest:
    variables:
      TIDB_PASSWORD:
        name: TIDB_PASSWORD
        type: secret
        valueFrom:
          secretKeyRef:
            name: sample-testvars
            key: TIDB_PASSWORD
    args:
      - "--summary-export"
      - "/home/k6/read-data.json"
      - tidb-readData-test.js 
    artifactRequest:
      dirs:
        - /home/k6
      masks:
        - .*\.json
      sharedBetweenPods: false
---