apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: csv-to-tidb-size1
  namespace: flink
spec:
  image: gaianmobius/test-flink-stream:0.0.111
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "32"
    kubernetes.taskmanager.node-selector: "dedicated:flink"
    kubernetes.taskmanager.tolerations: "key:dedicated,operator:Equal,value:flink,effect:NoSchedule"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "4096m"
      cpu: 1.0
  taskManager:
    resource:
      memory: "15Gi"
      cpu: 15.6
  job:
    jarURI: local:///opt/flink/usrlib/original-flink-demo-0.0.2.jar
    entryClass: flinkdemo.flinkdemo.FlinkDemoApplication
    parallelism: 32
    upgradeMode: stateless