apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: flink
  name: flink-session-cluster
spec:
  image: flink:1.17
  flinkVersion: v1_17
  flinkConfiguration:
    job.autoscaler.enabled: "true"
    job.autoscaler.stabilization.interval: "1m"
    job.autoscaler.metrics.window: "5m"
    job.autoscaler.target.utilization: "0.8"
    job.autoscaler.target.utilization.boundary: "0.3"
    pipeline.max-parallelism: "1"
    taskmanager.numberOfTaskSlots: "100"
  serviceAccount: flink
  mode: standalone
  jobManager:
    resource:
      memory: "1Gi"
      cpu: 1
  taskManager:
    resource:
      memory: "1Gi"
      cpu: 1
  maxReplicas: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: basic-hpa
  namespace: k6-operator-system
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: flink.apache.org/v1beta1
    kind: FlinkDeployment
    name: basic
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 10Mi
