apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: openmeter
  namespace: metering
spec:
  defaults:
    templates:
      podTemplate: pod-template-with-metrics
      serviceTemplate: svc-template
      dataVolumeClaimTemplate: openmeter-ch-data
  configuration:
    clusters:
      - name: openmeter
        layout:
          shardsCount: 1
          replicasCount: 0
    users:
      default/networks/ip: "::/0"
      openmeter/password_sha256_hex: 9f182fa055b7458a6768d651a9c504d8dbe42710787f83ecce6cee415d95048f
      openmeter/networks/ip:
        - 0.0.0.0/0
    settings:
      logger/level: "warning"
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
      prometheus/status_info: true
  templates:
    podTemplates:
      - name: pod-template-with-metrics
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              resources:
                requests:
                  cpu: "1000m"
              ports:
                - name: metrics
                  containerPort: 9363
    serviceTemplates:
      - name: svc-template
        generateName: chi-{chi}
        metadata:
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: metrics
              port: 9363
          type: ClusterIP                  
    volumeClaimTemplates:
      - name: openmeter-ch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
