apiVersion: v1
kind: Pod
metadata:
  name: mysql-client-pod
  namespace: tidb-cluster
  labels:
    app: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql:8.3.0
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: tidb-secret
          mountPath: /etc/tidb-secret 
          readOnly: true
      resources:
        limits:
          cpu: 20m
          memory: 50Mi
  volumes:
    - name: tidb-secret
      secret:
        secretName: tidb-tidb-client-secret
