apiVersion: v1
kind: Namespace
metadata:
  name: tidb-cluster
---  
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidb
  namespace: tidb-cluster
spec:
  version: v7.5.0
  timezone: UTC
  configUpdateStrategy: RollingUpdate
  pvReclaimPolicy: Delete
  topologySpreadConstraints:
    - topologyKey: topology.kubernetes.io/zone
  enableDynamicConfiguration: true
  helper:
    image: alpine:3.16.0
  tlsCluster:
    enabled: true
  ###########################
  # TiDB Cluster Components
  # PD is shared across share clusters
  # TiDB nodes are shared across shard clusters
  # TiKV nodes are dedicated for each shard cluster
  ###########################
  pd:
    storageClassName: default-csi
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 3
    enableDashboardInternalProxy: true
    requests:
      storage: "10Gi"
    #  validate using show placement labels; SHOW PLACEMENT;
    config: |
      [replication]
        location-labels = ["topology.kubernetes.io/region","topology.kubernetes.io/zone","kubernetes.io/hostname", "shard"]
        max-replicas = 3
      [security]
        cert-allowed-cn = [ "TiDB" ]
    tlsClientSecretName: tidb-pd-dashboard-client-secret
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 2000
    nodeSelector:
      dedicated: pd
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: pd
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - pd
          topologyKey: kubernetes.io/hostname
  tikv:
    storageClassName: ultra-csi
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 3
    requests:
      storage: "50Gi"
    config: |
      max-days = 1
      auto-adjust-pool-size = true
      [server]
        [rocksdb.titan]
          enabled = true
        [server.labels]
          shard = "shard-0"    
      [security]
        cert-allowed-cn = [ "TiDB" ]
    nodeSelector:
      dedicated: tikv
    labels:
      shard: shard-0  
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tikv
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - tikv
          topologyKey: kubernetes.io/hostname
  tidb:
    storageClassName: default-csi
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 2
    initializer:
      createPassword: true
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      exposeStatus: true
      externalTrafficPolicy: Local
      type: LoadBalancer
    config: |
      [performance]
        tcp-keep-alive = true
        max-procs = 0
      [security]
        cert-allowed-cn = [ "TiDB" ]
    annotations:
      tidb.pingcap.com/sysctl-init: "true"
    podSecurityContext:
      sysctls:
        - name: net.ipv4.tcp_keepalive_time
          value: "300"
        - name: net.ipv4.tcp_keepalive_intvl
          value: "75"
        - name: net.core.somaxconn
          value: "32768"
    separateSlowLog: true
    slowLogTailer:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
    tlsClient:
      enabled: true
    nodeSelector:
      dedicated: tidb
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tidb
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - tidb
          topologyKey: kubernetes.io/hostname
  ticdc:
    storageClassName: default
    baseImage: pingcap/ticdc
    replicas: 1
    config:
     security:
       cert-allowed-cn:
         - TiDB
---
# apiVersion: pingcap.com/v1alpha1
# kind: TidbClusterAutoScaler
# metadata:
#  name: tidb-as
# spec:
#  cluster:
#    name: tidb
#  tikv:
#    resources:
#      storage_small:
#        cpu: 1000m
#        memory: 2Gi
#        storage: 10Gi
#        count: 2
#    rules:
#      cpu:
#        max_threshold: 0.8
#        min_threshold: 0.2
#        resource_types:
#          - storage_small
#  tidb:
#    resources:
#      compute_small:
#        cpu: 1000m
#        memory: 2Gi
#        count: 3
#    rules:
#      cpu:
#        max_threshold: 0.8
#        min_threshold: 0.2
#        resource_types:
#          - compute_small